### ISSUE TITLE
Backup shop data at startup and then every 10 minutes as separate file, maximum of 10 backups

### ISSUE THREAD

**Issue by codenius** [DoctorFuchs/kiosk#36]

**Comment by DoctorFuchs** [comment]
# New Task:
Add a documentation how to rollback

**Comment by codenius** [comment]
Did it! 2cb69bf

**Comment by codenius** [comment]
###Next one
- Add panic button to frontend that saves last backup permanently and 
- show message that says that you should ask your admin for a restore

**Comment by DoctorFuchs** [comment]
instead of a panic button, we may need a function to undo the last actions. (Maybe saved in cookies)

**Comment by codenius** [comment]
> (Maybe saved in cookies)

Why not use a variable?

**Comment by DoctorFuchs** [comment]
Thats a question of frontend or backend, both is possible. I prefer frontend, because the action started here, so it's maybe easier to revert an action.

**Comment by codenius** [comment]
I meant a JavaScript runtime variable. Or do you think that it's required to keep this data over site refresh?

**Comment by DoctorFuchs** [comment]
Maybe it's more comfortable for users. At init we can get a json from a cookie
