### ISSUE TITLE
About site

### ISSUE THREAD

**Issue by codenius** [DoctorFuchs/kiosk#9]
Complete and improve the interactive in-app tutorial.

**Comment by DoctorFuchs** [comment]
I will remove it. So we can delete the sidebars

**Comment by codenius** [comment]
I think a button for the tutorial in an "About" tab in navbar would work best.

**Comment by DoctorFuchs** [comment]
Good idea, we delete "Kasse" and replace it with an about site.

**Comment by codenius** [comment]
The about page is good enough for now. Tutorial entry point will be on dashboard.
